package com.sgw.utils

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 */
object Triangles {
  /**
   * Returns an iterator over the set of triangle numbers.
   */
  def generate: Iterator[Long] = new Iterator[Long] {
    private var x = 0
    private var sum = 0

    def hasNext: Boolean = true

    def next = {
      x += 1
      sum += x
      sum
    }
  }
}
